### PR TITLE
Upstream 20160930

### PR DESCRIPTION
**Pull request by johnsyweb**
# Context

Upstream has moved on and so must we

# Considerations

Heroku scheduler will need updating
- Only call seal once per day
- Command-line is simply `./bin/seal.rb`

# Cc

@envato/marketplace

### CODE REVIEW

**Comment by gstamp** [comment]
+1

**Comment by orien** [comment]
+1

**Comment by jiexinhuang** [comment]
:+1: :tropical_fish:

**Comment by johnsyweb** [comment]
Thanks folks.

image

**Pull request merged**
